const Menu = [
    {
        id:1,
        category:"pending",
        button:[
            {
                name:"pending",
                color:"#1A1C1F",
                colors:"#FDF0CC",
            }
        ]
    },
    {
        id:2,
        category:"completed",
        button:[
            {
                name:"Completed",
                color:"#41B079",
                colors:"",
            }
        ]
    },
    {
        id:3,
        category:"pending",
        button:[
            {
                name:"Pending",
                color:"#1A1C1F",
                colors:"#FDF0CC",
            }
        ]
    },
    {
        id:4,
        category:"completed",
        button:[
            {
                name:"Completed",
                color:"#41B079",
                colors:"",
            }
        ]
    },
    {
        id:5,
        category:"pending",
        button:[
            {
                name:"Pending",
                color:"#1A1C1F",
                colors:"#FDF0CC",
            }
        ]
    },
    {
        id:6,
        category:"completed",
        button:[
            {
                name:"Completed",
                color:"#41B079",
                colors:"",
            }
        ]
    },
    {
        id:7,
        category:"pending",
        button:[
            {
                name:"Pending",
                color:"#1A1C1F",
                colors:"#FDF0CC",
            }
        ]
    },
    



]
export default Menu;